routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

		
	Route::group(['prefix' => 'David-Moreno'], function(){

		Route::get('/', function () {
    		return view('welcome');
		});
		Route::get('/home', 'HomeController@index');
		Route::resource('Article', 'Article\ArticleController');
		Route::resource('Category', 'Category\CategoryController');
		Route::resource('Information', 'Information\InformationController');
		Route::resource('Portafolio', 'Portafolio\PortafolioController');
		Route::resource('Tag', 'Tag\TagController');
		Route::resource('User', 'Auth\UserController');

		Route::get('Portafolio/{Portafolio}',[
			'as'	=>	'Portafolio.destroy',
			'uses'	=>	'Portafolio\PortafolioController@destroy'
		]);

		Route::get('Tag/{Tag}',[
			'as'	=>	'Tag.destroy',
			'uses'	=>	'Tag\TagController@destroy'
		]);

		Route::get('Category/{Category}',[
			'as'	=>	'Category.destroy',
			'uses'	=>	'Category\CategoryController@destroy'
		]);

		Route::get('Article/{Article}',[
			'as'	=>	'Article.destroy',
			'uses'	=>	'Article\ArticleController@destroy'
		]);

		Route::get('Categories/{name}',[
			'as'	=>	'Category.search',
			'uses'	=>	'Article\ArticleController@searchCategory'
		]);

		Route::get('Tags/{name}',[
			'as'	=>	'Tag.search',
			'uses'	=>	'Article\ArticleController@searchTag'
		]);

		
		
});
Auth::routes();

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index');

resources/views/articles.blade.php
@extends('layouts.app')

@section('header')

@endsection

@section('content')
@if (Auth::guest())
    @else
        <div class="pull-right">
             <a data-toggle="modal" data-target="#New" data-placement="bottom" title="Nuevo"><i class="btn fa fa-plus fa-4x" aria-hidden="true"></i></a>
        </div>
@endif
    <section class="main-section" id="service">
            <center>
                <h1>Articulos</h1>    
            </center>        
            

        <div class="container">
            <div class="row">
                <div class="col-md-8">
        
                    
                @foreach ($article as $article)
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            {{$article->name}}
                            <div class="pull-right"> Tags:
                                @foreach ($article->tags as $tag)
                                    {{$tag->name}}.
                                @endforeach
                            </div>
                        </div>
                            <div class="panel-body">
                                <h3>{!! $article->description!!}</h3>
                            </div>
                            <div class="panel-footer">
                                <div class="pull-right">
                                    {!! $article->updated_at->diffForHumans() !!}
                                </div>
                                @if (Auth::guest())
                                <p>Categoria:  {{$article->category->name}}</p>
                                @else
                                <p>Categoria:  {{$article->category->name}}</p>
                                    <center>

                                        <a href="{{route('Article.edit', $article->id)}}" data-toggle="tooltip" data-placement="bottom" title="Editar"><i class="btn fa fa-pencil fa-2x" aria-hidden="true"></i></a>
                                        <a href="{{route('Article.destroy', $article->id)}}" data-toggle="tooltip" data-placement="bottom" title="Eliminar"><i class="btn fa fa-trash fa-2x" aria-hidden="true"></i></a>
                                    </center>
                                @endif
                                
                            </div>
                        </div>

                @endforeach
                </div>
                
                <div class="col-md-4">
                    <div class="panel panel-primary">
                      <div class="panel-heading">Categorias</div>
                      <div class="panel-body">
                        @foreach ($categoria as $categoria)
                        <li class="list-group-item">
                            <a href="{{ route('Category.search', $categoria->name) }}">
                                {!! $categoria->name !!}
                            </a>
                            
                            <span class="badge">{!! $categoria -> articles -> count() !!}</span>
                        </li>
                        
                        @endforeach
                      </div>
                    </div>

                    <div class="panel panel-info">
                      <div class="panel-heading">Tags</div>
                      <div class="panel-body">
                        @foreach ($tags as $tags)
                        <a href="{{ route('Tag.search', $tags->name) }}">
                            <span class="badge">
                                {!! $tags -> name !!}
                            </span>
                        </a>
                        @endforeach
                      </div>
                    </div>

                </div>
            </div>
        </div>
    </section>

<!--
    Mis Modelas
-->
<!-- Agregar al portafolio -->
  <div class="modal fade" id="New" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Nuevo articulo</h4>
        </div>
        <div class="modal-body">
            {!! Form::open(['route' => 'Article.store', 'method' => 'POST', 'files' => true]) !!}
                

                <div class="form-group">
                    {!! Form::label('name_project', 'Nombre') !!}
                    {!! Form::text('name', null, ['class' =>'form-control textarea-personal', 'requerid', 'placeholder' => 'Nombre del articulo']) !!}
                </div>
                                        
                <div class="form-group">
                    {!! Form::label('description_project', 'Descripcion') !!}
                    {!! Form::textarea('description', null, ['class' =>'form-control textarea-academic', 'requerid', 'placeholder' => 'Descripcion del articulo']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('category_id', 'Prioridad',[ 'class' => 'col-md-4 control-label']) !!}
                    {!! Form::select('category_id', $category, null, ['class' => 'form-control category-select ','placeholder' => 'Seleccione una categoria', 'required']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('fk_priority_id', 'Requisitos de la historia',[ 'class' => ' control-label']) !!}
                    {!! Form::select('tag[]', $tag_article, null, ['class' => 'form-control tag-select ','placeholder' => 'Seleccione algunos tags', 'required','multiple']) !!}
                </div>
                <div class="form-group">
                    {!! Form::hidden('blog_id', 1) !!}
                </div>
        </div>
        <div class="modal-footer">
            <center>
                {!! Form::submit('Guardar', ['class' =>'btn btn-success']) !!}
            </center>
          {!! Form::close() !!}
        </div>
      </div>
      
    </div>
  </div>

@endsection

@section('js')
<script>
    $('#New').on('shown.bs.modal', function () {
        $('.tag-select', this).chosen({
        });

        $('.category-select', this).chosen({
        }); 
    });

    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });

    $('.textarea-academic').trumbowyg();
</script>
@endsection

resources/views/categories.blade.php
@extends('layouts.app')

@section('header')

@endsection

@section('content')
@if (Auth::guest())
    @else
        <div class="pull-right">
             <a data-toggle="modal" data-target="#New" data-placement="bottom" title="Nuevo"><i class="btn fa fa-plus fa-4x" aria-hidden="true"></i></a>
        </div>
@endif
    <section class="main-section" id="service">
        <center>
            <h1>Mis categorias</h1>
        </center>
        <div class="container">
            <div class="row">
                @foreach ($catefory as $catefory)
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <center>
                                    <h3><a href="#">{{$catefory->name}}</a></h3>
                                </center>
                            </div>
                            
                                <div class="panel-footer"> 
                                    <center>
                                        @if (Auth::guest())
                                            @else
                                                <a href="{{route('Category.edit', $catefory->id)}}" data-toggle="tooltip" data-placement="bottom" title="Editar"><i class="btn fa fa-pencil fa-2x" aria-hidden="true"></i></a>
                                                <a href="{{route('Category.destroy', $catefory->id)}}" data-toggle="tooltip" data-placement="bottom" title="Eliminar"><i class="btn fa fa-trash fa-2x" aria-hidden="true"></i></a> 
                                            @endif
                                            
                                            
                                    </center>
                                    </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>

<!--
    Mis Modelas
-->
<!-- Agregar al portafolio -->
  <div class="modal fade" id="New" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Nueva categoria</h4>
        </div>
        <div class="modal-body">
            {!! Form::open(['route' => 'Category.store', 'method' => 'POST', 'files' => true]) !!}
                

                <div class="form-group">
                    {!! Form::label('name_project', 'Nombre') !!}
                    {!! Form::text('name', null, ['class' =>'form-control textarea-personal', 'requerid', 'placeholder' => 'Nombre de la categoria']) !!}
                </div>
        </div>
        <div class="modal-footer">
            <center>
                {!! Form::submit('Guardar', ['class' =>'btn btn-success']) !!}
            </center>
          {!! Form::close() !!}
        </div>
      </div>
      
    </div>
  </div>

@endsection

@section('js')
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });

    $('.textarea-academic').trumbowyg();
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/information.blade.php
@extends('layouts.app')

@section('title')
	Mi información
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">@if (Auth::guest())
                        @else
                            <a data-toggle="modal" data-target="#myModal" data-toggle="tooltip" data-placement="bottom" title="Editar"><i class="btn fa fa-pencil pull-right" aria-hidden="true"></i></a>
                        @endif
                	<center>
                		<h2>
                			Informacion personal
                		</h2>
                		
                	</center>
                </div>
                <div class="panel-body">

                    <strong>{!! $information->personal_information !!}</strong>
                </div>
                <div class="panel-footer">
                	Ultima actualizacion {!! $information->updated_at->diffForHumans() !!}
                    
                </div>
            </div>
        </div>

        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading"><center><h2>Informacion academica</h2></center></div>
                <div class="panel-body">
                	
                    <strong>{!! $information-> acedemic_information !!}</strong>
                </div>
                 <div class="panel-footer">
                	Ultima actualizacion {!! $information->updated_at->diffForHumans() !!}
                    
                </div>
            </div>
        </div>

        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading"><center><h2>Mas sobre mi</h2></center></div>
                <div class="panel-body">
                	
                    <strong>{!! $information-> more_informacion !!}</strong>
                </div>
                 <div class="panel-footer">
                	Ultima actualizacion {!! $information->updated_at->diffForHumans() !!}
                </div>
            </div>
        </div>
    </div>
</div>



<!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Editar mi Informacion</h4>
        </div>
        <div class="modal-body">
            {!! Form::open(['route' => ['Information.update', $information->id], 'method' => 'PUT']) !!}
                

                <div class="form-group">
                    {!! Form::label('personal_information', 'Informacion Personal') !!}
                    {!! Form::textarea('personal_information', $information->personal_information, ['class' =>'form-control textarea-personal', 'requerid', 'placeholder' => 'Nombre de la peticion']) !!}
                </div>
                                        
                <div class="form-group">
                    {!! Form::label('acedemic_information', 'Informacion Academica') !!}
                    {!! Form::textarea('acedemic_information', $information->acedemic_information, ['class' =>'form-control textarea-academic', 'requerid', 'placeholder' => 'Descripcion de la peticion']) !!}
                </div>

                <div class="form-group">
                    {!! Form::label('more_informacion', 'Mas informacion') !!}
                    {!! Form::textarea('more_informacion', $information->more_informacion, ['class' =>'form-control textarea-more', 'requerid', 'placeholder' => 'Descripcion de la peticion']) !!}
                </div>

                <div class="form-group">
                    {!! Form::hidden('blog_id', $information->blog_id) !!}
                </div>

                <div class="modal-footer">
                    {!! Form::submit('Guardar', ['class' =>'btn btn-success col-md-offset-5']) !!}
                </div>

            {!! Form::close() !!}
        </div>
      </div>
      
    </div>
  </div>
@endsection

@section('js')
<script>
    $('.textarea-academic').trumbowyg({
       lang: 'es' 
    });
    $('.textarea-personal').trumbowyg({
        lang: 'es'
    });
    $('.textarea-more').trumbowyg({
        lang: 'es'
    });
</script>
@endsection

resources/views/landing.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @if (Auth::check())
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ url('/login') }}">Login</a>
                        <a href="{{ url('/register') }}">Register</a>
                    @endif
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Laravel
                </div>

                <div class="links">
                    <a href="https://laravel.com/docs">Documentation</a>
                    <a href="https://laracasts.com">Laracasts</a>
                    <a href="https://laravel-news.com">News</a>
                    <a href="https://forge.laravel.com">Forge</a>
                    <a href="https://github.com/laravel/laravel">GitHub</a>
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/portafolio.blade.php
@extends('layouts.app')

@section('title')
	Mi información
@endsection

@section('content')

@if (Auth::guest())
@else
    <div class="pull-right">
         <a data-toggle="modal" data-target="#New"><i class="btn fa fa-plus fa-4x" aria-hidden="true"></i></a>
    </div>
@endif
    <section class="main-section" id="service">
         
        <div class="container">
            <div class="row">
                @if(count($errors) >0)
        <div class="alert alert-danger" role="alert">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif
                
                @foreach ($image as $image)
                    <div class="col-md-12">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                @if (Auth::guest())
                                    <h3><a href="{{route('Portafolio.edit', $image->id)}}">{{$image->portafolio->name_project}}</a></h3>
                                @else
                                    <h3><a href="#">{{$image->portafolio->name_project}}</a></h3>
                                @endif
                                
                            </div>
                            <div class="panel-body">
                            	<center>
                            		<img src="/images/portafolio/{{$image->name}}" height="350">	
                            	</center>
                                
                                <div>
                                    <p>{!! $image->portafolio->description_project !!}</p>
                                </div>
                            </div>
                            @if (Auth::guest())
                                @else
                                    <div class="panel-footer">
                                        <center>
                                            <a href="{{route('Portafolio.edit', $image->id)}}" data-toggle="tooltip" data-placement="bottom" title="Editar"><i class="btn fa fa-pencil fa-2x" aria-hidden="true"></i></a>
                                            <a href="{{route('Portafolio.destroy', $image->id)}}" data-toggle="tooltip" data-placement="bottom" title="Eliminar"><i class="btn fa fa-trash fa-2x" aria-hidden="true"></i></a>
                                            <a href="{{$image->portafolio->url}}" data-toggle="tooltip" data-placement="bottom" title="{{$image->portafolio->url}}"><i class="btn fa fa-gitlab fa-2x" aria-hidden="true"></i></a>
                                            <div class="pull-right">
                                            <i class="fa fa-clock-o" aria-hidden="true"></i> {!! $image->portafolio->updated_at->diffForHumans() !!}
                                        </div>
                                        </center>
                                        
                                    </div>
                                @endif
                            
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>

<!--
    Mis Modelas
-->
<!-- Agregar al portafolio -->
  <div class="modal fade" id="New" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Nuevo folder</h4>
        </div>
        <div class="modal-body">
            {!! Form::open(['route' => 'Portafolio.store', 'method' => 'POST', 'files' => true]) !!}
                

                <div class="form-group">
                    {!! Form::label('name_project', 'Nombre') !!}
                    {!! Form::text('name_project', null, ['class' =>'form-control textarea-personal', 'requerid', 'placeholder' => 'Nombre del portafolio']) !!}
                </div>
                                        
                <div class="form-group">
                    {!! Form::label('description_project', 'Descripcion del portafolio') !!}
                    {!! Form::textarea('description_project', null, ['class' =>'form-control textarea-academic', 'requerid', 'placeholder' => 'Descripcion del portafolio']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('description_project', 'URL') !!}
                    {!! Form::textarea('url', null, ['class' =>'form-control textarea-academic', 'requerid', 'placeholder' => 'Por favor pegue la url del proyecto']) !!}
                </div>

                <div class="form-group">
                    {!! Form::hidden('blog_id', 1) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('image','Imagen') !!}
                    {!! Form::file('image', ['requerid']) !!}
                </div>
                
                
            
        </div>
        <div class="modal-footer">
            <center>
                {!! Form::submit('Guardar', ['class' =>'btn btn-success']) !!}
            </center>
          {!! Form::close() !!}
        </div>
      </div>
      
    </div>
  </div>

@endsection

@section('js')
<script>

</script>
@endsection

resources/views/tags.blade.php
@extends('layouts.app')

@section('header')

@endsection

@section('content')
@if (Auth::guest())
    @else
        <div class="pull-right">
             <a data-toggle="modal" data-target="#New" data-placement="bottom" title="Nuevo"><i class="btn fa fa-plus fa-4x" aria-hidden="true"></i></a>
        </div>
@endif
    <section class="main-section" id="service">
        <center>
            <h1>Mis Tags</h1>
        </center>
        <div class="container">
            <div class="row">
                
                @foreach ($tag as $tag)
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <center>
                                    <h3><a href="#">{{$tag->name}}</a></h3>
                                </center>
                            </div>
                            
                                <div class="panel-footer"> 
                                    <center>
                                        @if (Auth::guest())
                                            @else
                                                <a href="{{route('Tag.edit', $tag->id)}}" data-toggle="tooltip" data-placement="bottom" title="Editar"><i class="btn fa fa-pencil fa-2x" aria-hidden="true"></i></a>
                                                <a href="{{route('Tag.destroy', $tag->id)}}" data-toggle="tooltip" data-placement="bottom" title="Eliminar"><i class="btn fa fa-trash fa-2x" aria-hidden="true"></i></a> 
                                            @endif
                                            
                                            
                                    </center>
                                    </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>

<!--
    Mis Modelas
-->
<!-- Agregar al portafolio -->
  <div class="modal fade" id="New" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Nuevo tag</h4>
        </div>
        <div class="modal-body">
            {!! Form::open(['route' => 'Tag.store', 'method' => 'POST', 'files' => true]) !!}
                

                <div class="form-group">
                    {!! Form::label('name_project', 'Nombre') !!}
                    {!! Form::text('name', null, ['class' =>'form-control textarea-personal', 'requerid', 'placeholder' => 'Nombre del tag']) !!}
                </div>
        </div>
        <div class="modal-footer">
            <center>
                {!! Form::submit('Guardar', ['class' =>'btn btn-success']) !!}
            </center>
          {!! Form::close() !!}
        </div>
      </div>
      
    </div>
  </div>

@endsection

@section('js')
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });

    $('.textarea-academic').trumbowyg();
</script>
@endsection